### ISSUE TITLE
Extension KeyError

### ISSUE THREAD

**Issue by lyx0124** [lyx0124/WMW#9]
I just installed our extension to chrome. No problem in starting the server, but once I browse something I'm getting:
```
Starting server on host=localhost, port=3380
Traceback (most recent call last):
  File "run_server.py", line 67, in <module>
    server = WmwServer(cmdargs=args, server_address=(HOSTNAME, WMW_PORT), RequestHandlerClass=WmwRequestHandler)
  File "run_server.py", line 53, in __init__
    self.doc_finder = BingRelatedDocumentFinder()
  File "/Users/liuyuxiang/leonard/course/CS338/WMW/search/RelatedDocumentFinder.py", line 14, in __init__
    self._engine = BingSearchEngine()
  File "/Users/liuyuxiang/leonard/course/CS338/WMW/search/search.py", line 19, in __init__
    self._subscription_key = os.environ['BING_KEY']
  File "/Users/liuyuxiang/anaconda3/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'BING_KEY'
```

**Comment by mdarcy220** [comment]
The BING_KEY environment variable needs to be set.  I forgot to post this on Slack but just added a note on it.  (Not reposting here in order to keep the key confidential.)

**Comment by lyx0124** [comment]
follow up question, now I can open WMW in chrome, but upon clicking "begin search", I got:
```
...
...
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

**Comment by mdarcy220** [comment]
Have you done `pip install -r requirements.txt`?

**Comment by lyx0124** [comment]
Sorry, my bad. I have now. But here comes another problem:
```
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
```

**Comment by mdarcy220** [comment]
Interesting, I haven't seen this before.  Since this is different than the original issue, could you open a new issue and post that error message along with your python version and operating system?
